/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmu_swordbearer_audio_data_Receiver */

#ifndef _Included_xmu_swordbearer_audio_data_Receiver
#define _Included_xmu_swordbearer_audio_data_Receiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xmu_swordbearer_audio_data_Receiver
 * Method:    selectClip
 * Signature: ([SI)Z
 */
JNIEXPORT jboolean JNICALL Java_xmu_swordbearer_audio_data_Receiver_selectClip
  (JNIEnv *, jclass, jshortArray, jint);

/*
 * Class:     xmu_swordbearer_audio_data_Receiver
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xmu_swordbearer_audio_data_Receiver_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     xmu_swordbearer_audio_data_Receiver
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmu_swordbearer_audio_data_Receiver_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     xmu_swordbearer_audio_data_Receiver
 * Method:    createBufferQueueAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmu_swordbearer_audio_data_Receiver_createBufferQueueAudioPlayer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
